global_frame: /map
robot_base_frame: base_link
transform_tolerance: 0.5
footprint: [[0.12, 0.14], [0.12, -0.14], [-0.12, -0.14], [-0.12, 0.14]]
#always_send_full_costmap: false

static_map:
  enabled: true
  map_topic: /augmented_map # this declaration doesn't work, it must be remapped explicitly in the launch file of move_base
  subscribe_to_updates: true

obstacles_layer:
  enabled: true
  obstacle_range: 6.0
  raytrace_range: 8.5
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {topic: /scan,
                      sensor_frame: /laser,
                      data_type: LaserScan,
                      clearing: true,
                      marking: true}

inflation_layer:
  enabled: true
  inflation_radius: 2.5 # max. distance from an obstacle at which costs are incurred for planning paths
  cost_scaling_factor: 7.0 # exponential rate at which the obstacle cost drops off (default: 10)
