global_costmap:
  update_frequency: 0.8
  publish_frequency: 1

  static_map: true

  plugins:
    - {name: static_map, type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}