local_costmap:
  update_frequency: 0.7
  publish_frequency: 1

  static_map: false
  rolling_window: true

  width: 3
  height: 3
  resolution: 0.01
  origin_x: -1.5
  origin_y: -1.5

  plugins:
    - {name: obstacles_layer,      type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}