TrajectoryPlannerROS:

# Robot Configuration Parameters
 max_vel_x: 0.2
 min_vel_x: 0.01
 max_vel_theta: 2.5
 min_vel_theta: -2.5
 min_in_place_vel_theta: 0.4
 acc_lim_theta: 1.4
 acc_lim_x: 0.5
 acc_lim_y: 0.5
 holonomic_robot: false

# Trajectory Scoring Parameters
 meter_scoring: true
 occdist_scale:  0.01
 pdist_scale: 0.4
 gdist_scale: 0.2

# Goal Tolerance Parameters
 xy_goal_tolerance: 0.1
 yaw_goal_tolerance: 0.17
 latch_xy_goal_tolerance: true

# Forward Simulation Parameters
 sim_time: 1.0
 vx_samples: 3
 vtheta_samples: 20
 sim_granularity: 0.025
